brand:
  name: PHGas
menu-string: Menu

nav:
  - title: Services
    url: '#services'
  - title: Quote
    url: '#quote'
  - title: Contact
    url: '#contact'

social-buttons:
  - icon: fab fa-instagram
    url: 'https://instagram.com/phgas'