brand:
  name: PHGas
menu-string: Menu

covid-message:
  title: 'COVID-19 UPDATE'
  line1: 'We want to reassure you that we are still open for business and our services are still running as normal.'
  line2: 'We care about keeping you and our community safe, so we’re taking extra precautions to protect and prevent COVID-19 spread.'

nav:
  - title: Services
    url: '#services'
  - title: Quote
    url: '#quote'
  - title: Contact
    url: '#contact'

social-buttons:
  - icon: fab fa-instagram
    url: 'https://instagram.com/phgas'
